version: '3.8'

services:
  windows-rdp:
    image: dockurr/windows
    environment:
      - VERSION=10
      - DISK_SIZE=256G
      - RAM_SIZE=8G
      - CPU_CORES=4
      - USERNAME=bill
      - PASSWORD=gates
      - LANGUAGE=English
      - QEMU_OPTS=-accel tcg -netdev user,id=net0 -device virtio-net-pci,netdev=net0
    ports:
      - "3389:3389"
    restart: unless-stopped
