version: '3.8'

services:
  windows-rdp:
    image: dockurr/windows
    container_name: windows-rdp
    environment:
      - VERSION=10
      - DISK_SIZE=256G
      - RAM_SIZE=8G
      - CPU_CORES=4
      - USERNAME=billkent
      - PASSWORD=gates
      - LANGUAGE=English
      - RDP_RESOLUTION=1920x1080
      - RDP_SESSION=rdp
      - RDP_AUDIO=rdp
      - RDP_CLIPBOARD=both
      - RDP_PRINTER=rdp
      - RDP_USB=rdp
    ports:
      - "3389:3389"  # RDP port
      - "8000:8000"  # Optional: web interface if available
    restart: unless-stopped
    privileged: true  # Required for KVM acceleration
    devices:
      - /dev/kvm:/dev/kvm  # KVM device for hardware acceleration
      - /dev/vhost-net:/dev/vhost-net  # Network acceleration
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    networks:
      - windows-net
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4'
        reservations:
          memory: 4G
          cpus: '2'

networks:
  windows-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
