version: '3.8'

services:
  windows-vm:
    build: .
    ports:
      - "8080:8080"  # HTTP port for Render detection
      - "3389:3389"  # RDP port
      - "5900:5900"  # VNC port
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4'
