version: '3'
services:
  firefox:
    build: .
    ports:
      - "5800:5800"
    volumes:
      - ./firefox-data:/config  # Persist sessions locally
    shm_size: "2gb"             # Fix performance issues
