FROM dockurr/windows

# Set all required environment variables
ENV VERSION="10"
ENV DISK_SIZE="256G"
ENV RAM_SIZE="8G"
ENV CPU_CORES="4"
ENV USERNAME="bill"
ENV PASSWORD="gates"
ENV LANGUAGE="English"
ENV RDP_RESOLUTION="1920x1080"
ENV ACCELERATION="none"
ENV TUN_NETDEV="off"
ENV USER_PORTS="on"
ENV MTU="1500"
ENV QEMU_NETDEV="user"

# Expose RDP port
EXPOSE 3389

