services:
  - type: web
    name: windows-rdp
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: VERSION
        value: "10"
      - key: DISK_SIZE
        value: "256G"
      - key: RAM_SIZE
        value: "8G"
      - key: CPU_CORES
        value: "4"
      - key: USERNAME
        value: "bill"
      - key: PASSWORD
        value: "gates"
      - key: LANGUAGE
        value: "English"
      - key: RDP_RESOLUTION
        value: "1920x1080"
    plan: standard
    numInstances: 1
    resources:
      memoryMB: 8192
      cpuCount: 4
    healthCheckPath: /health
    port: 3389
